export const ACTIONS = {
  VIEW_CATALOG: "VIEW_CATALOG",
  TRACK_READING: "TRACK_READING",
  RAISE_QUERY: "RAISE_QUERY",
  CHECKOUT_BOOK: "CHECKOUT_BOOK",
  PURCHASE_BOOK: "PURCHASE_BOOK",
  REQUEST_BOOK: "REQUEST_BOOK",
  CREATE_P2P_LISTING: "CREATE_P2P_LISTING",
  EDIT_P2P_LISTING: "EDIT_P2P_LISTING",
  DELETE_P2P_LISTING: "DELETE_P2P_LISTING",
  BUY_P2P: "BUY_P2P",
  BORROW_P2P: "BORROW_P2P",
  SCAN_BOOK: "SCAN_BOOK",
  APPROVE_P2P: "APPROVE_P2P",
  MANAGE_INVENTORY: "MANAGE_INVENTORY",
} as const;

export type Action = (typeof ACTIONS)[keyof typeof ACTIONS];
